name: fitness_ui
description: "Flutter Fitness App."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: 0.14.3
  intl: ^0.20.2
  flutter_layout_grid: 2.0.8
  flutter_rating_bar: 4.0.1
  go_router: 15.0.0
  flutter_riverpod: 2.6.1
  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  firebase_ui_auth: ^1.17.0
  google_sign_in: ^6.3.0
  firebase_ui_oauth_google: ^1.4.2
  http: ^1.4.0
  sembast: ^3.8.5+1
  sembast_web: ^2.4.2
  path_provider: ^2.1.5
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 5.0.0

# Custom app icon. For more info see: https://pub.dev/packages/flutter_launcher_icons
flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/app-icon.png"
  image_path_android: "assets/app-icon.png"
  # https://github.com/fluttercommunity/flutter_launcher_icons/issues/144
  adaptive_icon_background: "assets/app-icon-background.png"
  adaptive_icon_foreground: "assets/app-icon-foreground.png"
  macos:
    generate: true
    image_path: "assets/app-icon.png"
  web:
    generate: true
    image_path: "assets/app-icon.png"

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    - assets/
