// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6yY4Tj_Y9Lmhjo2Jo1xHfrih1MEhVqjA',
    appId: '1:739786523479:ios:4bc850fe0f84ab1a54f412',
    messagingSenderId: '739786523479',
    projectId: 'fitness-app-1d202',
    storageBucket: 'fitness-app-1d202.firebasestorage.app',
    iosClientId: '739786523479-cnner6a5ehigbcbkuon6n52a4ha4kfbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessUi',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD94eU8H_OzN77HSylWwsSyoNMm-RpQESI',
    appId: '1:739786523479:web:2a38123f134b51ee54f412',
    messagingSenderId: '739786523479',
    projectId: 'fitness-app-1d202',
    authDomain: 'fitness-app-1d202.firebaseapp.com',
    storageBucket: 'fitness-app-1d202.firebasestorage.app',
    measurementId: 'G-6ZG7N247ZQ',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6yY4Tj_Y9Lmhjo2Jo1xHfrih1MEhVqjA',
    appId: '1:739786523479:ios:4bc850fe0f84ab1a54f412',
    messagingSenderId: '739786523479',
    projectId: 'fitness-app-1d202',
    storageBucket: 'fitness-app-1d202.firebasestorage.app',
    iosClientId: '739786523479-cnner6a5ehigbcbkuon6n52a4ha4kfbb.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessUi',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs-1_PwWZOMQgUQqpLp8ZsZqW8qq-UOHc',
    appId: '1:739786523479:android:8cd6ac4263aa444954f412',
    messagingSenderId: '739786523479',
    projectId: 'fitness-app-1d202',
    storageBucket: 'fitness-app-1d202.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD94eU8H_OzN77HSylWwsSyoNMm-RpQESI',
    appId: '1:739786523479:web:b0a320a2a1e636dc54f412',
    messagingSenderId: '739786523479',
    projectId: 'fitness-app-1d202',
    authDomain: 'fitness-app-1d202.firebaseapp.com',
    storageBucket: 'fitness-app-1d202.firebasestorage.app',
    measurementId: 'G-7R2YET917S',
  );

}